---
- name: Atualiza os facts forçadamente
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Executa o Job Template que atualiza os facts
      ansible.controller.job_launch:
        controller_host: https://controller.lab5.example.com
        controller_username: admin
        controller_password: redhat
        job_template: Coleta de facts do parque
        wait: true
      register: job
...
